# Generated by Django 5.2.4 on 2026-01-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_player_isavailable_alter_customuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="isAvailable",
            field=models.BooleanField(default=True),
        ),
    ]
