# Generated by Django 5.2.4 on 2026-01-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_alter_player_isavailable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="teamName",
        ),
        migrations.AlterField(
            model_name="manager",
            name="customUser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="tournament.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="customUser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to="tournament.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="customUser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referee",
                to="tournament.customuser",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=50, unique=True)),
                (
                    "manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="tournament.manager",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="tournament.team",
            ),
        ),
    ]
